require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'vendor/**/*'
    - 'lib/cloudkeeper_grpc/*'

Metrics/LineLength:
  Max: 135
  Exclude:
    - 'lib/cloudkeeper/one/appliance_actions/list.rb'

Metrics/LineLength:
  Max: 140
  Include:
    - 'lib/cloudkeeper/one/core_connector.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/MethodLength:
  Max: 20
  Include:
    - 'lib/cloudkeeper/one/appliance_actions/list.rb'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/cloudkeeper/one/appliance_actions/list.rb'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'lib/cloudkeeper/one/cli.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 3

RSpec/NestedGroups:
  Max: 4

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
    - 'lib/cloudkeeper/grpc/*'
