cloudkeeper-one:
  listen-address: 127.0.0.1:50051 # IP address gRPC server will listen on
  identifier: cloudkeeper-one # Instance identifier
  appliances:
    tmp-dir: /var/spool/cloudkeeper-one/appliances # Directory where to temporarily store appliances
    template-dir: # If set, templates within this directory are used to construct images and templates in OpenNebula
    permissions: "640" # UNIX-like permissions appliances will have within OpenNebula
  opennebula:
    secret: oneadmin:opennebula # If not specified, looking for secret in environment variable ONE_AUTH and file ~/.one/one_auth
    endpoint: http://localhost:2633/RPC2 # If not specified, looking for endpoint in environment variable ONE_XMLRPC and file ~/.one/one_endpoint
    datastores: # Array of OpenNebula datastores images will be uploaded to
      - default
    groups: # Array of groups. If set, groups from image list will be ignored and these groups will be used instead
    users: # Handle only images/templates of specified users
    api-call-timeout: 3h # How long will cloudkeeper-one wait for image/template operations to finish in OpenNebula
  logging:
    level: ERROR # Logging level
    file: /var/log/cloudkeeper/cloudkeeper-one.log # File to write log to. To turn off file logging leave this field empty.
  debug: false # Debug mode
