cloudkeeper-one:
  listen-address: 127.0.0.1:50051 # IP address gRPC server will listen on
  authentication: false # core (client) <-> backend (server) authentication (certificate, key and core-certificate options)
  certificate: /etc/grid-security/hostcert.pem # Backend's host certificate
  key: /etc/grid-security/hostkey.pem # Backend's host key
  identifier: cloudkeeper-one # Instance identifier
  core:
    certificate: /etc/grid-security/corecert.pem # Core's certificate
  appliances:
    tmp-dir: /var/spool/cloudkeeper/appliances # Directory where to temporarily store appliances
    template-dir: # If set, templates within this directory are used to construct images and templates in OpenNebula
    permissions: "640" # UNIX-like permissions appliances will have within OpenNebula
  opennebula:
    secret: oneadmin:opennebula # If not specified, looking for secret in environment variable ONE_AUTH and file ~/.one/one_auth
    endpoint: http://localhost:2633/RPC2 # If not specified, looking for endpoint in environment variable ONE_XMLRPC and file ~/.one/one_endpoint
    datastore: default # OpenNebula datastore images will be uploaded to
    api-call-timeout: 3h # How long will cloudkeeper-one wait for image/template operations to finish in OpenNebula
    allow-remote-source: true # Allows OpenNebula to directly download remote image
  logging:
    level: ERROR # Logging level
    file: /var/log/cloudkeeper/cloudkeeper-one.log # File to write log to. To turn off file logging leave this field empty.
  debug: false # Debug mode
